[project]
name = "cover_dist"
version = "v0.7"
authors = [
    { name = "p1geondove", email = "leo.peil@web.de" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=74.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cover_dist = ["*.pyi", "py.typed"]

[[tool.setuptools.ext-modules]]
name = "cover_dist._core"
sources = ["src/cover_dist/_core.c"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
