[project]
name = "coverdist"
version = "0.4"
authors = [
    { name = "p1geondove", email = "leo.peil@web.de" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[[tool.setuptools.ext-modules]]
name = "coverdist"
sources = ["cover_dist.c"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
